# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d86dd9b4af1801f5301ffe1cbc9d95a8154b0b07d1e8a53d6162d4036e6262659fdad9a58ee60a4e38e95d51c6696c606ceab55efa2cc9ce7817d823bb5fc7a2

test:
  secret_key_base: 3fe323a67ba3119f8c7cedcabe17dfda5db72812f483d01827282b1e99792bb5418414f1d82a57f13b90452f2ccc62806e8930561f63db629ef6dea87ff0d98b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
